services:
  - type: web
    name: iris-classification-api
    env: python
    buildCommand: pip install -r api/requirements.txt
    startCommand: cd api && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

